apiVersion: dbaas.redhat.com/v1alpha1
kind: RDSInstance
metadata:
  name: rdsinstance-sample
  namespace: rds-sample
spec:
  inventoryRef:
    name: rdsinventory-sample
    namespace: rds-sample
  provisioningParameters:
    name: rds-instance-sample
    plan: DEDICATED
    cloudProvider: AWS
    databaseType: postgres
    availabilityZones: us-east-1a
    machineType: db.t3.micro
    storageGib: "20"

