name: Build Image

on:
  pull_request:
    branches:
      - main
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Image build
        uses: redhat-actions/buildah-build@v2
        with:
          image: dbaas-operator
          platforms: linux/amd64
          containerfiles: |
            ./Dockerfile
