name: Go generate

on:
  push:
    branches:
    - main
    - release-*
  pull_request:
    branches:
    - main
    - release-*

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate manifests and bundle
        run: make bundle
      - name: After code and manifest generation, check for uncommitted differences
        run: git diff --exit-code
